spring.application.name=pt-wiremock

# Custom Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# Custom API Docs path
springdoc.api-docs.path=/api-docs

# Actuator
management.endpoints.web.exposure.include=info,health,metrics,prometheus
management.endpoint.health.show-details=always
management.info.git.mode=full
management.server.port=8081
management.endpoint.health.show-details=always

